### ISSUE TITLE
hey thats mine :)

### ISSUE THREAD

**Issue by Fweak** [Leaked0/21k-dollars-discord-account-creator#1]

**Comment by 1x6** [comment]
interesting

**Comment by ghost** [comment]
this is going to be skidded asl, clean code though

**Comment by HideakiAtsuyo** [comment]
> _No description provided._

Ah RIP no idea someone sent it to me :joy:

**Comment by HideakiAtsuyo** [comment]
But personally I wouldn't have wasted my time making several files for this I would have just put everything together out of laziness :eyes:

**Comment by post04** [comment]
> But personally I wouldn't have wasted my time making several files for this I would have just put everything together out of laziness 👀

fweak didn't actually make that gen, that gen is woens but the bypasses used in it are me and fweaks which is why he said it's his lol. Fweak would never write such ratchet code

**Comment by post04** [comment]
Both discord side bypasses and hcaptcha bypasses are fweak and mines

**Comment by HideakiAtsuyo** [comment]
> > But personally I wouldn't have wasted my time making several files for this I would have just put everything together out of laziness 👀
> 
> fweak didn't actually make that gen, that gen is woens but the bypasses used in it are me and fweaks which is why he said it's his lol. Fweak would never write such ratchet code

Yeah ikr :)

**Comment by Fweak** [comment]
> Both discord side bypasses and hcaptcha bypasses are fweak and mines

There's a funny part to this. This is easily bypassable if hcaptcha and discord cared LMFAO. I can dm you how they would detect it and we can make changes to the gen so we evade it.

**Comment by Gowixx** [comment]
lol + they took down the api

**Comment by HideakiAtsuyo** [comment]
> lol + they took down the api

Lol not that hard to up the api

**Comment by Gowixx** [comment]
ye u just do `node .` in the bypass/browser

**Comment by HideakiAtsuyo** [comment]
> ye u just do `node .` in the bypass/browser

But I don't even need their api too lmao

**Comment by CssHammer** [comment]
can i bypass it with regular captcha solving services?

**Comment by HideakiAtsuyo** [comment]
> can i bypass it with regular captcha solving services?

Yes
